Repository Sella-GH/AzzyBot, pull requests merged in 2024-04, with the labels that each got.

#19 General reconstructure
  AzzyBot/AzzyBot.cs
  AzzyBot/Commands/Attributes/RequireUserRoleAttribute.cs
  AzzyBot/ExceptionHandling/DiscordClientError.cs
  AzzyBot/ExceptionHandling/ExceptionHandler.cs
  AzzyBot/Modules/AzuraCast/AzuraCastEmbedBuilder.cs
  AzzyBot/Modules/AzuraCast/AzuraCastModule.cs
  AzzyBot/Modules/AzuraCast/AzuraCastServer.cs
  AzzyBot/Modules/AzuraCast/AzuraCastSettings.cs
  AzzyBot/Modules/AzuraCast/AzuraCastStats.cs
  AzzyBot/Modules/BaseModule.cs
  AzzyBot/Modules/BaseSettings.cs
  AzzyBot/Modules/ClubManagement/ClubControls.cs
  AzzyBot/Modules/ClubManagement/ClubEmbedBuilder.cs
  AzzyBot/Modules/ClubManagement/ClubManagementCommands.cs
  AzzyBot/Modules/ClubManagement/ClubManagementModule.cs
  AzzyBot/Modules/ClubManagement/ClubManagementSettings.cs
  AzzyBot/Modules/Core/CoreAzzyHelp.cs
  AzzyBot/Modules/Core/CoreAzzyStatsGeneral.cs
  AzzyBot/Modules/Core/CoreCommands.cs
  AzzyBot/Modules/Core/CoreFileOperations.cs
  AzzyBot/Modules/Core/CoreModule.cs
  AzzyBot/Modules/Core/CoreSettings.cs
  AzzyBot/Modules/Core/Updater/UpdaterMisc.cs
  AzzyBot/Modules/Core/Updater/UpdaterModel.cs
  AzzyBot/Modules/Core/Updater/Updates.cs
  AzzyBot/Modules/MusicStreaming/MusicStreamingCommands.cs
  AzzyBot/Modules/MusicStreaming/MusicStreamingLavalink.cs
  AzzyBot/Modules/MusicStreaming/MusicStreamingLavalinkHandler.cs
  AzzyBot/Modules/MusicStreaming/MusicStreamingModule.cs
  AzzyBot/Modules/MusicStreaming/MusicStreamingSettings.cs
  AzzyBot/Modules/MusicStreaming/Player/MusicStreamingPlayer.cs
  AzzyBot/Strings/StringBuilding.cs
  CHANGELOG.md
Labels: enhancement

#20 Create new docker images for every new branch
  .github/workflows/docker.yml
  Dockerfile
Labels: enhancement, dependencies

#21 Refactor Updater inside Azzy
  .editorconfig
  .github/workflows/docker.yml
  .github/workflows/dotnet-release-publish.yml
  .github/workflows/dotnet.yml
  AzzyBot/AzzyBot.cs
  AzzyBot/Customization/Core/StringsCore.json
  AzzyBot/Modules/AzuraCast/AzuraCastEmbedBuilder.cs
  AzzyBot/Modules/AzuraCast/AzuraCastModule.cs
  AzzyBot/Modules/AzuraCast/AzuraCastServer.cs
  AzzyBot/Modules/ClubManagement/ClubEmbedBuilder.cs
  AzzyBot/Modules/ClubManagement/ClubManagementCommands.cs
  AzzyBot/Modules/ClubManagement/ClubManagementModule.cs
  AzzyBot/Modules/Core/CoreCommands.cs
  AzzyBot/Modules/Core/CoreEmbedBuilder.cs
  AzzyBot/Modules/Core/CoreFileOperations.cs
  AzzyBot/Modules/Core/CoreModule.cs
  AzzyBot/Modules/Core/CoreSettings.cs
  AzzyBot/Modules/Core/CoreWebRequests.cs
  AzzyBot/Modules/Core/Updater/UpdaterMisc.cs
  AzzyBot/Modules/Core/Updater/UpdaterModel.cs
  AzzyBot/Modules/Core/Updater/Updates.cs
  AzzyBot/Modules/MusicStreaming/MusicStreamingModule.cs
  AzzyBot/Settings/appsettings.json
  AzzyBot/Strings/Core/CoreStringBuilder.cs
  AzzyBot/Strings/Core/CoreStringModel.cs
  CHANGELOG.md
Labels: enhancement

#23 Replace txt info files with a json one
  .github/workflows/dotnet-release-publish.yml
  .github/workflows/dotnet.yml
  AzzyBot/AzzyBot.csproj
  AzzyBot/AzzyBot.json
  AzzyBot/Modules/Core/CoreAzzyStatsGeneral.cs
  AzzyBot/Modules/Core/CoreFileLock.cs
  AzzyBot/Modules/Core/CoreModule.cs
  AzzyBot/Modules/Core/Enums/CoreFileNamesEnum.cs
  AzzyBot/Modules/Core/Enums/CoreFileValuesEnum.cs
  AzzyBot/Modules/Core/Models/AzzyBotModel.cs
  CHANGELOG.md
  Dockerfile
Labels: enhancement

#24 Enhance `core info azzy` embedd
  .github/workflows/docker.yml
  .github/workflows/dotnet-release-publish.yml
  .github/workflows/dotnet.yml
  AzzyBot/AzzyBot.cs
  AzzyBot/AzzyBot.json
  AzzyBot/Customization/Core/StringsCore.json
  AzzyBot/Modules/Core/CoreAzzyStatsGeneral.cs
  AzzyBot/Modules/Core/CoreEmbedBuilder.cs
  AzzyBot/Modules/Core/CoreFileLock.cs
  AzzyBot/Modules/Core/Enums/CoreFileValuesEnum.cs
  AzzyBot/Modules/Core/Models/AzzyBotModel.cs
  AzzyBot/Strings/Core/CoreStringBuilder.cs
  AzzyBot/Strings/Core/CoreStringModel.cs
  CHANGELOG.md
  Dockerfile
Labels: enhancement

#27 Ci issues
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/workflows/docker.yml
  .github/workflows/dotnet-release-publish.yml
  .github/workflows/dotnet.yml
Labels: enhancement

#29 Consolidate and improve logging
  AzzyBot/AzzyBot.cs
  AzzyBot/AzzyBot.csproj
  AzzyBot/Commands/Attributes/RequireUserRoleAttribute.cs
  AzzyBot/ExceptionHandling/DiscordClientError.cs
  AzzyBot/ExceptionHandling/SlashCommandError.cs
  AzzyBot/Logging/LoggerBase.cs
  AzzyBot/Logging/LoggerExceptions.cs
  AzzyBot/Modules/AzuraCast/AcCommands.cs
  AzzyBot/Modules/AzuraCast/AcModule.cs
  AzzyBot/Modules/AzuraCast/Settings/AcSettings.cs
  AzzyBot/Modules/AzuraCast/Strings/AcStringBuilder.cs
  AzzyBot/Modules/BaseSettings.cs
  AzzyBot/Modules/ClubManagement/CmCommands.cs
  AzzyBot/Modules/ClubManagement/CmModule.cs
  AzzyBot/Modules/ClubManagement/CmTimer.cs
  AzzyBot/Modules/ClubManagement/Settings/CmSettings.cs
  AzzyBot/Modules/ClubManagement/Strings/CmStringBuilder.cs
  AzzyBot/Modules/Core/CoreAzzyStatsGeneral.cs
  AzzyBot/Modules/Core/CoreAzzyStatsLinux.cs
  AzzyBot/Modules/Core/CoreCommands.cs
  AzzyBot/Modules/Core/CoreFileLock.cs
  AzzyBot/Modules/Core/CoreFileOperations.cs
  AzzyBot/Modules/Core/CoreModule.cs
  AzzyBot/Modules/Core/CoreTimer.cs
  AzzyBot/Modules/Core/CoreWebRequests.cs
  AzzyBot/Modules/Core/Settings/CoreSettings.cs
  AzzyBot/Modules/Core/Strings/CoreStringBuilder.cs
  AzzyBot/Modules/ModuleStates.cs
  AzzyBot/Modules/MusicStreaming/MsCommands.cs
  AzzyBot/Modules/MusicStreaming/MsLavalinkHandler.cs
  AzzyBot/Modules/MusicStreaming/Settings/MsSettings.cs
  AzzyBot/Modules/MusicStreaming/Strings/MsStringBuilder.cs
Labels: enhancement

#30 Add file cache to docker.zip
  .github/workflows/dotnet-release-publish.yml
  .github/workflows/dotnet.yml
  docker-compose.dev.yml
  docker-compose.yml
Labels: docker

#31 Add support for Non-HTTP-Proxy Streams
  AzzyBot/Modules/AzuraCast/Settings/AcSettings.cs
  AzzyBot/Modules/BaseSettings.cs
  AzzyBot/Modules/MusicStreaming/MsLavalink.cs
  AzzyBot/Modules/MusicStreaming/Settings/MsSettings.cs
  AzzyBot/Settings/appsettings.json
Labels: enhancement

#32 Check if Strings are correctly set before allowing the bot to start
  AzzyBot/AzzyBot.cs
  AzzyBot/Modules/AzuraCast/Strings/AcStringBuilder.cs
  AzzyBot/Modules/BaseSettings.cs
  AzzyBot/Modules/BaseStringBuilder.cs
  AzzyBot/Modules/ClubManagement/Strings/CmStringBuilder.cs
  AzzyBot/Modules/Core/Strings/CoreStringBuilder.cs
  AzzyBot/Modules/MusicStreaming/Strings/MsStringBuilder.cs
Labels: enhancement

#34 Replace `Ping` with `GET`s to be more accurate
  AzzyBot/AzzyBot.cs
  AzzyBot/Modules/AzuraCast/AcModule.cs
  AzzyBot/Modules/AzuraCast/AcStats.cs
  AzzyBot/Modules/AzuraCast/Settings/AcSettings.cs
  AzzyBot/Modules/Core/CoreWebRequests.cs
  CHANGELOG.md
Labels: refactoring

#35 Uncluster AzuraCast Update notifications
  AzzyBot/Customization/AzuraCast/StringsAzuraCast.json
  AzzyBot/Modules/AzuraCast/AcEmbedBuilder.cs
  AzzyBot/Modules/AzuraCast/AcModule.cs
  AzzyBot/Modules/AzuraCast/Strings/AcStringBuilder.cs
  AzzyBot/Modules/AzuraCast/Strings/AcStringModel.cs
Labels: refactoring

#37 Changing key values - CoreSettings
  AzzyBot/Settings/appsettings.json
Labels: bug, good first issue

#38 Unify AzuraCast pre-checks
  AzzyBot/Commands/Attributes/RequireAzuraApiKeyValid.cs
  AzzyBot/Commands/Attributes/RequireMusicServerUp.cs
  AzzyBot/ExceptionHandling/SlashCommandError.cs
  AzzyBot/Modules/AzuraCast/AcCommands.cs
Labels: refactoring

#40 Change to `System.Text.Json`
  AzzyBot/Modules/AzuraCast/AcEmbedBuilder.cs
  AzzyBot/Modules/AzuraCast/AcServer.cs
  AzzyBot/Modules/AzuraCast/AcStats.cs
  AzzyBot/Modules/AzuraCast/Autocomplete/AcFavoriteSongAutocomplete.cs
  AzzyBot/Modules/AzuraCast/Models/AcConfigSlogansModel.cs
  AzzyBot/Modules/AzuraCast/Models/AcFavoriteSongModel.cs
  AzzyBot/Modules/AzuraCast/Models/AcFilesModel.cs
  AzzyBot/Modules/AzuraCast/Models/AcListenerModel.cs
  AzzyBot/Modules/AzuraCast/Models/AcNowPlayingModel.cs
  AzzyBot/Modules/AzuraCast/Models/AcPlaylistItemModel.cs
  AzzyBot/Modules/AzuraCast/Models/AcPlaylistModel.cs
  AzzyBot/Modules/AzuraCast/Models/AcSongHistoryModel.cs
  AzzyBot/Modules/AzuraCast/Models/AcSongModel.cs
  AzzyBot/Modules/AzuraCast/Models/AcSongRequestsModel.cs
  AzzyBot/Modules/AzuraCast/Models/AcSongRequestsQueueModel.cs
  AzzyBot/Modules/AzuraCast/Models/AcStationConfigModel.cs
  AzzyBot/Modules/AzuraCast/Models/AcStatsModel.cs
  AzzyBot/Modules/AzuraCast/Models/AcUpdateModel.cs
  AzzyBot/Modules/AzuraCast/Strings/AcStringBuilder.cs
  AzzyBot/Modules/ClubManagement/CmClubControls.cs
  AzzyBot/Modules/ClubManagement/Models/CmBotStatusModel.cs
  AzzyBot/Modules/ClubManagement/Strings/CmStringBuilder.cs
  AzzyBot/Modules/Core/CoreFileLock.cs
  AzzyBot/Modules/Core/Models/AzzyBotModel.cs
  AzzyBot/Modules/Core/Strings/CoreStringBuilder.cs
  AzzyBot/Modules/Core/Updater/UpdaterModel.cs
  AzzyBot/Modules/Core/Updater/Updates.cs
  AzzyBot/Modules/MusicStreaming/Strings/MsStringBuilder.cs
Labels: refactoring

#41 Add new check to command exec if Station is online
  AzzyBot/Commands/Attributes/RequireMusicStationUp.cs
  AzzyBot/ExceptionHandling/SlashCommandError.cs
  AzzyBot/Modules/AzuraCast/AcCommands.cs
  AzzyBot/Modules/AzuraCast/AcServer.cs
  AzzyBot/Modules/AzuraCast/Models/AcNowPlayingModel.cs
  AzzyBot/Modules/AzuraCast/Models/AcStationModel.cs
  AzzyBot/Modules/MusicStreaming/MsLavalink.cs
Labels: enhancement
